### ISSUE TITLE
Add more stats to the replays

### ISSUE THREAD

**Issue by slavabez** [Cryptyc/SC2LadderWebHost#4]
Add more nice statistics to pages, including win/loss of bots vs other bots, avg game time, etc.

I'm looking into how to do that

**Comment by slavabez** [comment]
@Cryptyc do you mind if I change the structure of the project a little? I want to move all the web files into a separate folder (www), and use the root directory for readme/gitignore and development docker files, just to keep it a little clean and prevent clutter

**Comment by slavabez** [comment]
See [https://github.com/slavabez/SC2LadderWebHost](https://github.com/slavabez/SC2LadderWebHost) for what I mean, is that kind of structure OK?

**Comment by Cryptyc** [comment]
Looks good, make a pull requiest and I'll integrate it across.  Currently I have the site auto update from the repo, so need to modify that first,

**Comment by slavabez** [comment]
Let me know if I can help with that, I've got some experience with that

**Comment by slavabez** [comment]
Heyo! Is the project still used? Wondering if I can close this issue so that I don't have open issues

**Comment by Cryptyc** [comment]
yeh, this will be retired when we do the next season, which should be pretty soon.  We're moving to a new site
