### ISSUE TITLE
FAQ outdated

### ISSUE THREAD

**Issue by Archiatrus** [Cryptyc/SC2LadderWebHost#9]
The faq is a little outdated. Also, to make it easier for new people you could directly link to a "how to start" guide. Aka:

**How Do I get on bot on the ladder?**
Compile you code into an executable file. Then either upload through your profile, or add a download link. 
The format should be similar to the way the sc2api examples are structured. You should follow [this](https://github.com/Cryptyc/CryptBot/blob/master/CryptbotMain.cpp) example as for how to connect to the LadderManager software. If you are just starting [here](http://wiki.sc2ai.net/CommandCenter_Getting_started_for_the_Ladder_Manager) you can find a guide explaining how to start with a generic bot you can use as starting point (recommanded). If you instead want to start with a blank bot use [this](http://wiki.sc2ai.net/Getting_started_for_the_Ladder_Manager_from_scratch) guide.
Once you register your bot, it will need to be verified to check for crashes etc. and will be entered into the next season.

**Can I update my bot?**
Yes. A continuous ELO rating is used to encourage well rounded bots and not "one trick ponies".

**How long do seasons last?**
There is no end date set yet.

**Can I watch bot matches without loading the replay file?**
The bot matches get streamed occasionally on [twitch.tv](https://www.twitch.tv/cryptious). If the stream is offline check out the videos section.

The links are
https://github.com/Cryptyc/CryptBot/blob/master/CryptbotMain.cpp
http://wiki.sc2ai.net/CommandCenter_Getting_started_for_the_Ladder_Manager
http://wiki.sc2ai.net/Getting_started_for_the_Ladder_Manager_from_scratch
https://www.twitch.tv/cryptious

**Comment by Cryptyc** [comment]
New FAQ uploaded
